@startuml state_diagram
[*] --> LoadState

LoadState --> Options

LoadState --> Error: [wrong datapath]

Options --> AddObject: [select add_object option]
Options --> GenerateNewState: [select generate option]
Options --> MakeStep: [select make_step option]
Options --> MakeSeveralSteps: [select make_several_steps option]
Options --> ShowState: [select show option]
Options --> Help: [select help option]
Options --> Error: [used wrong option]

Help --> [*]

AddObject --> Error: [wrong object type]
AddObject --> Error: [invalid coordinates]

MakeSeveralSteps --> Error: [invalid num of steps]

AddObject --> ShowState
GenerateNewState --> ShowState
MakeStep --> ShowState
MakeSeveralSteps --> ShowState

ShowState --> SaveStateAndExit

Error --> [*]

SaveStateAndExit --> [*]

AddObject: add choosen type of object by given coordinates

MakeStep: make new step of simulation

MakeSeveralSteps: make given num of steps of simulation

GenerateNewState: create new randomized simulation

Help: show possible options

@enduml